### ISSUE TITLE
请问大佬，这个前端代码如何运行

### ISSUE THREAD

**Issue by chengda1992** [hjdhnx/drpy-node#1]
![image](https://github.com/user-attachments/assets/f6fe9cd2-1129-4b4b-a6b1-5898ccd75b31)

**Comment by chengda1992** [comment]
![image](https://github.com/user-attachments/assets/182e00e8-7c71-42d3-8a72-3e89c15e6a15)
pnpm 运行报错

**Comment by Hiram-Wong** [comment]
> ![image](https://private-user-images.githubusercontent.com/42691983/392203448-f6fe9cd2-1129-4b4b-a6b1-5898ccd75b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNzM4MzMsIm5iZiI6MTczNDM3MzUzMywicGF0aCI6Ii80MjY5MTk4My8zOTIyMDM0NDgtZjZmZTljZDItMTEyOS00YjRiLWE2YjEtNTg5OGNjZDc1YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE4MjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NmUyNDRjMmRkODkyOTU1MDVjYmJhYjRlMmExNzE1Yjc0NmU2YzAxYTgzNDljNzU1MTFlYWNhOGI3NjY5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0YelJHvUJoKQbpVuVv3dLIlJZe06ngKC7GQqDzkWLek)


node版本 太低导致，最低要求 18+
